export const cleanConsole = (text: string) => {
    return text
      .replace(/("[^"]*"|'[^']*'|`[^`]*`)/g, '<span class="text-blue-300">$1</span>')
      .replace(/&lt;\//g, '<span class="text-blue-500">&lt;/</span>')
      .replace(/&lt;/g, '<span class="text-blue-500">&lt;</span>')
      .replace(/&gt;/g, '<span class="text-blue-500">&gt;</span>')
      .replace(/div/g, '<span class="text-blue-500">div</span>')
      .replace(/className/g, '<span class="text-orange-500">className</span>')
      .replace(/ id/g, '<span class="text-green-500"> id</span>')
      .replace(/style/g, '<span class="text-purple-500">style</span>')
      .replace(/onClick/g, '<span class="text-yellow-500">onClick</span>')
      .replace(/onMouseEnter/g, '<span class="text-yellow-500">onMouseEnter</span>')
      .replace(/onMouseLeave/g, '<span class="text-yellow-500">onMouseLeave</span>')
      .replace(/{/g, '<span class="text-yellow-500">{</span>')
      .replace(/}/g, '<span class="text-yellow-500">}</span>')
      .replace(/\(/g, '<span class="text-emerald-500">(</span>')
      .replace(/\)/g, '<span class="text-emerald-500">)</span>')
      .replace(/.map/g, '<span class="text-emerald-500">.map</span>')
      .replace(/\$/g, '<span class="text-yellow-500">$</span>')
      .replace(/backgroundImage/g, '<span class="text-yellow-500">backgroundImage</span>')
      .replace(/=>/g, '<span class="text-yellow-500">=></span>')
      .replace(/true/g, '<span class="text-pink-300">true</span>')
      .replace(/false/g, '<span class="text-pink-300">false</span>')
      .replace(/key/g, '<span class="text-green-500">key</span>')
      .replace(/\?/g, '<span class="text-blue-500">?</span>')
      .replace(/===/g, '<span class="text-blue-500">===</span>')
      .replace(/:/g, '<span class="text-blue-500">:</span>')
      .replace(/Icon /g, '<span class="text-yellow-500">Icon</span>')
      .replace(/Icon/g, '<span class="text-yellow-500">Icon</span>')
      .replace(/ChevronLeft/g, '<span class="text-yellow-500">ChevronLeft</span>')
      .replace(/ChevronRight/g, '<span class="text-yellow-500">ChevronRight</span>')
      .replace(/import/g, '<span class="text-purple-500">import</span>')
      .replace(/from /g, '<span class="text-red-500"> from </span>')
      .replace(/use client/g, '<span class="text-slate-400">use client</span>')
      .replace(/useState/g, '<span class="text-sky-500">useState</span>')
      .replace(/useEffect/g, '<span class="text-sky-500">useEffect</span>')
      .replace(/useCallback/g, '<span class="text-sky-500">useCallback</span>')
      .replace(/useMemo/g, '<span class="text-sky-500">useMemo</span>')
      .replace(/const/g, '<span class="text-pink-500">const</span>')
      .replace(/react/g, '<span class="text-emerald-500">react</span>')
      .replace(/-bootstrap-icons/g, '<span class="text-emerald-500">-bootstrap-icons</span>')
      .replace(/\[/g, '<span class="text-emerald-500">[</span>')
      .replace(/\]/g, '<span class="text-emerald-500">]</span>')
      .replace(/return/g, '<span class="text-emerald-500">return</span>')
      .replace(/export /g, '<span class="text-yellow-500">export </span>')
      .replace(/default /g, '<span class="text-orange-300">default </span>')
      .replace(/function /g, '<span class="text-purple-300">function </span>')
      .replace(/.length/g, '<span class="text-yellow-500">.length</span>');
  };
  console.log(cleanConsole)